### ISSUE TITLE
5.1 class def

### ISSUE THREAD

**Issue by peoplemerge** [makuk66/docker-solr#5]
5.0 has been working great.  Just went to 5.1 docker image, now on startup I get:

Caused by: java.lang.NoSuchMethodError: org.apache.solr.core.SolrCore.getRequestHandlers()Ljava/util/Map;
    at org.apache.solr.handler.dataimport.DataImportHandler.inform(DataImportHandler.java:100)

Possibly a 5.1 error?  Suspected solr-dataimporthandler jar not in cp but solrconfig has it in the right place:   <lib dir="/opt/solr/dist/" regex="solr-dataimporthandler-.*\.jar" />

IMO /opt/solr/dist/solr-dataimporthandler-5.1.0.jar should match.  So I'm scratching my head...

**Comment by vthacker** [comment]
Since I didn't have that path I tried with these lib directives and it worked fine on 5.1

```
  <lib dir="${solr.install.dir:../../../..}/contrib/extraction/lib" regex=".*\.jar" />
  <lib dir="${solr.install.dir:../../../..}/dist/" regex="solr-cell-\d.*\.jar" />

  <lib dir="${solr.install.dir:../../../..}/contrib/clustering/lib/" regex=".*\.jar" />
  <lib dir="${solr.install.dir:../../../..}/dist/" regex="solr-clustering-\d.*\.jar" />

  <lib dir="${solr.install.dir:../../../..}/contrib/langid/lib/" regex=".*\.jar" />
  <lib dir="${solr.install.dir:../../../..}/dist/" regex="solr-langid-\d.*\.jar" />

  <lib dir="${solr.install.dir:../../../..}/contrib/velocity/lib" regex=".*\.jar" />
  <lib dir="${solr.install.dir:../../../..}/dist/" regex="solr-velocity-\d.*\.jar" />

  <lib dir="${solr.install.dir:../../../..}/dist/" regex="solr-dataimporthandler-.*\.jar" />
```

```
~/solr-5.1.0 $ ls dist/
solr-analysis-extras-5.1.0.jar      solr-dataimporthandler-extras-5.1.0.jar solr-test-framework-5.1.0.jar
solr-analytics-5.1.0.jar        solr-langid-5.1.0.jar           solr-uima-5.1.0.jar
solr-cell-5.1.0.jar         solr-map-reduce-5.1.0.jar       solr-velocity-5.1.0.jar
solr-clustering-5.1.0.jar       solr-morphlines-cell-5.1.0.jar      solrj-lib
solr-core-5.1.0.jar         solr-morphlines-core-5.1.0.jar      test-framework
solr-dataimporthandler-5.1.0.jar    solr-solrj-5.1.0.jar
```

**Comment by makuk66** [comment]
peoplemerge: does this still happen with the latest, 5.2.1? If so can you include specific steps to reproduce?
